### ISSUE TITLE
Contribute challenges

### ISSUE THREAD

**Issue by CodeWithMa** [Tobertet/ToberQuizz#7]
Hello,

I found your nice app on fdroid. I could contribute German challenges. How do I do that? Should I create a PR? I looked at the source code and it looks like you removed the challenges from there.

Maybe add a Wiki entry about how to contribute challenges in new languages.

**Comment by Tobertet** [comment]
Hello @CodeWithMa, sorry for the late response. For some reason Github did not send me an email and I did not notice a new issue had been open.

It would be awesome adding new countries to the app! There are only a few things that need to be done. 
1. Register the new country with the 2 letter ISO in the CountryCode.ts file.
2. Add the translations for german in src/i18n/locales/de.json
3. Send me the challenge proposal with both the assets and the hashed answers. I will prepare a wiki for this specific point today so it is more clear what needs to be done exactly.

You are right, I had to remove the challenges from here because the bundle size was increasing drastically. Now they are hosted at supabase, that is why the application got flagged with a non-free network antifeature.

Would you mind creating a PR with the german translations? There are only a few items. If not I can use google translate but I would have no idea if the translation is fine.

**Comment by Tobertet** [comment]
I just published a wiki page with instructions on generating the challenge resources https://github.com/Tobertet/ToberQuizz/wiki/Proposing-a-new-challenge

I created a new issue template with the required data for creating a new challenge. Feel free to close this issue and open a new one following that template.

If you find anything confusing let me know and I will try to rephrase it.

**Comment by CodeWithMa** [comment]
Thanks for your reply :)

> Would you mind creating a PR with the german translations? There are only a few items. If not I can use google translate but I would have no idea if the translation is fine.

Yes I will create a PR for that.

> I just published a wiki page with instructions on generating the challenge resources https://github.com/Tobertet/ToberQuizz/wiki/Proposing-a-new-challenge
> 
> I created a new issue template with the required data for creating a new challenge. Feel free to close this issue and open a new one following that template.
> 
> If you find anything confusing let me know and I will try to rephrase it.

Okay. I will take a look at the wiki page later and create a new issue when I'm ready with my challenges.
